### PR TITLE
Update s3.adoc

### PR DESCRIPTION
**Pull request by derKrischan**
Document optional endpoint property for alternative S3 endpoints.

Fixes #?

### CODE REVIEW

**Comment by aalmiray** [comment]
Thank you for the PR. The endpoint property was left undocumented as I believe is not yet fully functional.

**Comment by derKrischan** [comment]
I just tested it successfully with a local S3 storage system by Cloudian. In the beginning I wanted to create a feature request but than discovered in source code that the property is already implemented as I would have suggested. 
I thought the main problem would be a test environment. Perhaps the property can be marked as experimental? Then other users can report problems or success stories with their own S3 systems if they are aware that the general support is available.

**Comment by aalmiray** [comment]
Thank you for letting me know. I think that the code needs an update for resolving the correct download URL when a custom endpoint is in use https://github.com/jreleaser/jreleaser/blob/ded153ccc1b44e88e8049b1c699f2b211b6ffa65/core/jreleaser-model/src/main/java/org/jreleaser/model/S3.java#L76

Any tips will be greatly appreciated.

**Comment by derKrischan** [comment]
I doubt there is an alway-fit-pattern to determine the download URL for custom S3 implementations and think that users using a custom endpoint should be experienced enough to customise the download URL as well.
In my case where the endpoint is "s3-{{region}}.example.com" (ignoring the fact that {{region}} cannot be used as a variable in endpoint definition) the change to determine the Download-URL with a custom endpoint automatically might look like:

```
    @Override
    public String getResolvedDownloadUrl(JReleaserContext context, Artifact artifact) {
        if (isNotBlank(getResolvedDownloadUrl())) {
            Map<String, Object> p = new LinkedHashMap<>(artifactProps(context, artifact));
            p.putAll(getResolvedExtraProperties());
            p.put("bucket", bucket);
            p.put("region", region);
            return applyTemplate(getResolvedDownloadUrl(), p);
        }

        if (isBlank(getResolvedEndpoint())) {
            String url = "https://{{bucket}}.s3.{{region}}.amazonaws.com/" + getResolvedPath();
            Map<String, Object> p = new LinkedHashMap<>(artifactProps(context, artifact));
            p.putAll(getResolvedExtraProperties());
            p.put("bucket", bucket);
            p.put("region", region);
            return applyTemplate(url, p);
        } else {
            String url = "https://{{bucket}}.{{endpoint}}/" + getResolvedPath();
            Map<String, Object> p = new LinkedHashMap<>(artifactProps(context, artifact));
            p.putAll(getResolvedExtraProperties());
            p.put("bucket", bucket);
            p.put("region", region);
            return applyTemplate(url, p);
        }

        return "";
    }
```

**Comment by aalmiray** [comment]
Thanks. Makes me think that downloadUrl should be set as a template aware property, default to amazon's patter when you use aws. This new property should be explicitly set if endpoint is set as well. WDYT?

**Comment by derKrischan** [comment]
Sounds good to me.

**Pull request merged**
