### PR TITLE
docs: migrate to homebrew-core

### PR DESCRIPTION
**Pull request by chenrui333**
👋 it would be good to include this project into homebrew-core so that it can be more easily distribute it out. Let me know what you folks think. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/119432

### CODE REVIEW

**Comment by aalmiray** [comment]
That would be amazing however currently we don't build core formulas that may be added to homebrew-core. Also we ship ready made binaries and core formulas prefer to build from source. I think a few exceptions have been made to that rule.

**Comment by chenrui333** [comment]
> That would be amazing however currently we don't build core formulas that may be added to homebrew-core. Also we ship ready made binaries and core formulas prefer to build from source. I think a few exceptions have been made to that rule.

building from source is generally true, but for java formulae, there are some debate about it.

**Comment by chenrui333** [comment]
BTW, the homebrew-core PR is ready to be merged, but just raising this one for the feedback.

Maintaining the core tap is super easy as well, can be done via these two actions
- https://github.com/mislav/bump-homebrew-formula-action (like cli/cli)
- https://github.com/dawidd6/action-homebrew-bump-formula (like infracost)

We have projects using both approaches.

**Comment by aalmiray** [comment]
Thanks for writing a PR to homebrew-core! Somehow I missed it. However, I see a few issues with the proposed formula:

- it declares a dependency on openjdk without defining a particular version. Fortunately JReleaser works with Java 8+ but that will change in the future where Java 11 will be set as the minimum.
- the test is performed generating a file instead of checking for the version as it's done in the tap https://github.com/jreleaser/homebrew-tap/blob/master/Formula/jreleaser.rb

Instead of depending on openjdk (we did that many months ago) JReleaser's brew formula expects binaries that ship with their own bundled JDK. I think these binaries are not currently supported by the Homebrew rules, which IMHO is the wrong thing to do. The whole point of bundling a Java Runtime is to ensure the correct JR is available to run the program instead of expecting a given JR provided by the system to be the right one.

**Comment by chenrui333** [comment]
> * it declares a dependency on openjdk without defining a particular version. Fortunately JReleaser works with Java 8+ but that will change in the future where Java 11 will be set as the minimum.

It would be always depending on the latest openjdk unless it cannot.

> * the test is performed generating a file instead of checking for the version as it's done in the tap https://github.com/jreleaser/homebrew-tap/blob/master/Formula/jreleaser.rb

We (homebrew) always look for more tests to ensure the binary run correctly, in other words, the formula should include non-trivial test to prove its correctness. In many cases, it does help catch some bugs.

**Comment by chenrui333** [comment]
> Instead of depending on openjdk (we did that many months ago) JReleaser's brew formula expects binaries that ship with their own bundled JDK. I think these binaries are not currently supported by the Homebrew rules, which IMHO is the wrong thing to do. The whole point of bundling a Java Runtime is to ensure the correct JR is available to run the program instead of expecting a given JR provided by the system to be the right one.

I did not know jreleaser has a bundled JRE, that is interesting. I might need to update the formula a bit later depending on the feedback that we've got.

**Comment by aalmiray** [comment]
Gotcha. Thank you for the explanation. As I recall the use of bundled JRs is discouraged, I found about that when investigating a fix for https://github.com/jreleaser/jreleaser/issues/675

dylibs ended getting corrupted and I was told that bundling a JR was frowned upon.

**Comment by aalmiray** [comment]
FWIW switching to the universal zip (non bundled JR) as you have it in the linked PR _with_ a dependency on openjdk will also work if that makes the formula compliant with core requirements.

**Comment by aalmiray** [comment]
@chenrui333 looks like the merge as successful! Thank you for setting this up. Now the question is how to keep the formula up to date when a new release is posted. In theory only the zip and checksum will change as new versions get posted. This could be automated during the JReleaser release process.

**Comment by chenrui333** [comment]
> FWIW switching to the universal zip (non bundled JR) as you have it in the linked PR _with_ a dependency on openjdk will also work if that makes the formula compliant with core requirements.

Aha, then, that is the same approach that I took for my formula

re autobump formula

> Maintaining the core tap is super easy as well, can be done via these two actions
> 
> * https://github.com/mislav/bump-homebrew-formula-action (like cli/cli)
> * https://github.com/dawidd6/action-homebrew-bump-formula (like infracost)

> UPDATE: Just re-read the thread about auto-updates. The COMMITTER_TOKEN should have permissions to write to the homebrew-core repository, shouldn't it?

write permission to a homebrew-core fork repo.

**Comment by aalmiray** [comment]
> write permission to a homebrew-core fork repo.

Ah OK. Which means fork is updated on release then send a PR to core repository, right?

**Pull request closed without merging**
